### ISSUE TITLE
Shortcode

### ISSUE THREAD

**Issue by meugamer** [mtoensing/wp-shortscore#11]
Marc, do you have any options that I can generate a short code inside the php code to position in a certain area of the site, instead of the end of the post?

**Comment by mtoensing** [comment]
What are you trying to accomplish? Do you want to put it somewhere in the single.php template file? You could write another function like that to provide a shortcode and commit it for a pull request.

**Comment by meugamer** [comment]
I sent the translation of the language into Portuguese, did you receive to include in your git?

**Comment by mtoensing** [comment]
No there are no pull requests https://github.com/mtoensing/wp-shortscore/pulls and no submitted languages: https://translate.wordpress.org/projects/wp-plugins/wp-shortscore/ Sorry. Where did you send it?
