### ISSUE TITLE
(requested) Code Review: "wp-shortscore.php"

### ISSUE THREAD

**Issue by C0DE8** [mtoensing/wp-shortscore#8]
- classname ("WP_SHORTSCORE ") only with upper case letter ans underscore
  => better: use CamelCase (i.e. "WpShortcode")
- missing a lot of class and method comments (header)
  => better: comment **all** classs, methods
- method ordering confusing =>better: use ordering: public, protected, private
- class definition and instantiation inside one file
  => better: user separate files
- 'https://shortscore.org' is private var
  => better: use  class constant
  `const SHORTCODE_URL = 'https://shortscore.org';`
- condition `if($error_code) {` not 100% clear 
  => better: use `if(false !==$error_code && !empty($error_code)) {`
- use of closing PHP Tag (?>) inside class
  => better: use HEREDOC (http://php.net/manual/de/language.types.string.php#language.types.string.syntax.heredoc)

**Comment by mtoensing** [comment]
done. =)

**Comment by C0DE8** [comment]
Thanks ;-)
